#!/bin/bash

# check package dependance
if [ -z "$(which scrot)" ]; then
    echo "Sorry, but scrot is required"
    exit 1
fi

FONT="$HOME/.fonts/NotoSansCJKkr-Regular.otf"
# Dependencies: imagemagick, i3lock-color-git, scrot

# get path where the script is located
# it's used for the lock icon
pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null

#quotegenProgram="/home/tanuj/Code/build-quotesCategories-Desktop-Debug/quotesCategories"
#quotegenProgram="$SCRIPTPATH/quoteGeneratorSnapshot" # uncomment this after building the c++ program

IMAGE=$(mktemp ~/screenshot/XXXXXXXX.png)
FULLTEXT="`shuf -n 1 $SCRIPTPATH/quotes.txt`"
firstchar="`echo ${FULLTEXT:0:1}`"
TEXT="\"`echo ${FULLTEXT:1}`\""

#default icons, these values will be overwritten
LOCKICONREG="lock"
LOCKICONDARK="lockdark"

## guide to quote codes: i = IT Crowd, s = Star Wars, p = Harry Potter
## l = Sherlock, m = meme, a = Hamilton
case "$firstchar" in
    "s")
        LOCKICONREG="empireLogoWhite"
        LOCKICONDARK="empireLogo"
        ;;
    "j")
        LOCKICONREG="jediwhite"
        LOCKICONDARK="jedi"
        ;;
    "a")
        LOCKICONREG="hamiltonwhite"
        LOCKICONDARK="hamiltonblack"
        ;;
    *)
        LOCKICONREG="icon2"
        LOCKICONDARK="icon2white"
        ;;
esac

# l10n support
case $LANG in
        fr_* ) TEXT="Entrez votre mot de passe" ;; # Français
        es_* ) TEXT="Ingrese su contraseña" ;; # Española
        pl_* ) TEXT="Podaj hasło" ;; # Polish
esac

VALUE="60" #brightness value to compare to
rm -f $IMAGE
while [ ! -s $IMAGE ]; do
    scrot -u $IMAGE
    COLOR=`convert $IMAGE -colorspace hsb -resize 1x1 txt:- | sed -e '/hsb/!d;s/.*hsb//;s/.*,//;s/%.*//;/^$/d'`
    sleep 1s
done
# pixelate: -scale 10% -scale 1000%
# sigma was 1.5

if [ "$COLOR" -gt "$VALUE" ]; then #white background image and black text
    convert $IMAGE -level 0%,100%,0.6 \
        -filter Gaussian -resize 20% -define filter:sigma=8.5 -resize 500.5% \
        -font $FONT -pointsize 32 -fill black  -gravity center \
        -annotate +0+160 "$TEXT" \
        $SCRIPTPATH/images/$LOCKICONDARK.png -gravity center -composite $IMAGE
    PARAM='--textcolor=00000000 --insidecolor=0ad65c1c --ringcolor=0000003e \
        --linecolor=00000000 --keyhlcolor=74e85888 --ringvercolor=ffffff00 \
        --insidevercolor=ffffff1c --ringwrongcolor=ffffff55 --insidewrongcolor=bf09095c'
else #black background with light text
    convert $IMAGE -level 0%,100%,0.6 \
        -filter Gaussian -resize 20% -define filter:sigma=8.5 -resize 500.5% \
        -font $FONT -pointsize 32 -fill white -gravity Center \
        -annotate +0+160 "$TEXT" \
        $SCRIPTPATH/images/$LOCKICONREG.png -gravity center -composite $IMAGE
    PARAM='--textcolor=ffffff00 --insidecolor=0ad65c6c --ringcolor=ffffff3e \
        --linecolor=ffffff00 --keyhlcolor=74e85888 --ringvercolor=00000000 \
        --insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=bf20151c'
fi

# try to use a forked version of i3lock with prepared parameters
i3lock $PARAM -i $IMAGE > /dev/null 2>&1

if [ $? -ne 0 ]; then
    # We have failed, lets get back to stock one
    i3lock -i $IMAGE
fi

rm $IMAGE
sleep 1 && xdotool type " " && xdotool key BackSpace
